<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <UserSecretsId>e3d6f798-5b40-4a1d-8a6c-a5060b602679</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\blossom\Sparc.Blossom.Data.Cosmos\Sparc.Blossom.Data.Cosmos.csproj" />
    <ProjectReference Include="..\..\blossom\Sparc.Blossom\Sparc.Blossom.csproj" />
    <ProjectReference Include="..\..\blossom\Sparc.Core\Sparc.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\starfield\" />
  </ItemGroup>

</Project>
